# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'p1.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys
from PyQt5.QtWidgets import *
from PyQt5.QtGui import QIcon

#Se definen los elementos con su nombre y sus coordenadas dentro de la pantalla MainWindow
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(725, 586)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton('Mostrar texto',self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(348, 380, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(398, 120, 141, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(398, 210, 141, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(398, 310, 191, 31))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(178, 440, 121, 31))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(488, 440, 141, 31))
        self.label_5.setObjectName("label_5")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(80, 120, 261, 22))
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(78, 160, 261, 131))
        self.textEdit.setObjectName("textEdit")
        self.spinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox.setGeometry(QtCore.QRect(79, 310, 261, 22))
        self.spinBox.setObjectName("spinBox")
        self.spinBox.setMinimum(1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(178, 480, 113, 22))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(498, 480, 113, 22))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(260, 10, 211, 31))
        self.label_6.setObjectName("label_6")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 725, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
#Funcion para poner etiquetas
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Analizar"))
        self.label.setText(_translate("MainWindow", "Nombre del archivo"))
        self.label_2.setText(_translate("MainWindow", "Texto a escribir"))
        self.label_3.setText(_translate("MainWindow", "Numero de lineas en el archivo"))
        self.label_4.setText(_translate("MainWindow", "Numero de vocales"))
        self.label_5.setText(_translate("MainWindow", "Numero de consonantes"))
        self.label_6.setText(_translate("MainWindow", "PyQt y el diseño de interfaz grafica"))
        #Linea de codigo para ir a la funcion analizar cuando se presione el boton de la pantalla
        self.pushButton.clicked.connect(self.analizar)

#Funcion para obtener los valores que ingrese el usuario
#para hacer el conteo de vocales y consonantes
    def analizar(self):
        nombre_archivo = self.lineEdit.text()
        file= open(nombre_archivo+".txt", "w+")
        text = self.textEdit.toPlainText()
        num = self.spinBox.value()
        count=0
        count2=0
        vocales = ["a", "e", "i", "o", "u"]
        consonantes = ["b", "c", "d", "f", "g", "h", "j", "k", "l", "m", "n", "p", "q", "r", "s", "t", "v", "w", "x", "y", "z"]
        #Guarda en el documento el texto n veces
        for x in range(0, num):
            file.writelines(text)
            file.write("\n")
            file.write("\n")
        #Contador de vocales y consonantes
        for i in text:
            if i.lower() in vocales:
                count += 1
            elif i.lower() in consonantes:
                count2 += 1
        #Se imprime en la MainWindow el numero de vocales y consonantes
        self.lineEdit_2.setText(str(count*num))
        self.lineEdit_3.setText(str(count2*num))
        


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
